# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 61c17ea4916618c78dc3322fc243ded4
  secret_key: 1e1cb2a8b61936b487c3ff2fb90b775a
  canvas_page_name: corinna_test
  callback_url: http://biascica.pipps.net:8888
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: lrnz
    public_host: biascica.pipps.net
    public_port: 8888
    local_port: 3000
    server_alive_interval: 60

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 18ce473f0a38bc39c51ed6e551bde130
  secret_key: 113e84ea583a5e9de8d4233a2ff1d83e
  canvas_page_name: corinna
  callback_url: http://xanadu.doesntexist.com/corinna
  set_asset_host_to_callback_url: true   
  api: new
#  tunnel:
#    public_host_username:
#    public_host:
#    public_port: 4007
#    local_port: 3000
#    server_alive_interval: 0

